// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelRoomLight.proto

package grpc.example.smarthotel;

public final class SmartHotelRoomLightProto {
  private SmartHotelRoomLightProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHotelRoom_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHotelRoom_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHotelRoom_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHotelRoom_LightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SmartHotelRoomLight.proto\022\016SmartHotelR" +
      "oom\" \n\014LightRequest\022\020\n\010roomarea\030\001 \001(\t\" \n" +
      "\rLightResponse\022\017\n\007success\030\001 \001(\0102\264\001\n\023Smar" +
      "tHotelRoomLight\022M\n\014TurnonLights\022\034.SmartH" +
      "otelRoom.LightRequest\032\035.SmartHotelRoom.L" +
      "ightResponse\"\000\022N\n\rTurnoffLights\022\034.SmartH" +
      "otelRoom.LightRequest\032\035.SmartHotelRoom.L" +
      "ightResponse\"\000B5\n\027grpc.example.smarthote" +
      "lB\030SmartHotelRoomLightProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartHotelRoom_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartHotelRoom_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHotelRoom_LightRequest_descriptor,
        new java.lang.String[] { "Roomarea", });
    internal_static_SmartHotelRoom_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartHotelRoom_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHotelRoom_LightResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
