// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelRoomPerformance.proto

package grpc.example.smarthotelroomperformance;

public interface ControlRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.example.smarthotelroomperformance.ControlRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string control_type = 1;</code>
   */
  java.lang.String getControlType();
  /**
   * <code>string control_type = 1;</code>
   */
  com.google.protobuf.ByteString
      getControlTypeBytes();

  /**
   * <code>string action = 2;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 2;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();
}
