// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelRoomPerformance.proto

package grpc.example.smarthotelroomperformance;

public final class RoomPerformance3 {
  private RoomPerformance3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_example_smarthotelroomperformance_SettingRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_example_smarthotelroomperformance_SettingRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_example_smarthotelroomperformance_SettingRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_example_smarthotelroomperformance_SettingRoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_example_smarthotelroomperformance_ControlRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_example_smarthotelroomperformance_ControlRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_example_smarthotelroomperformance_ControlRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_example_smarthotelroomperformance_ControlRoomResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037SmartHotelRoomPerformance.proto\022&grpc." +
      "example.smarthotelroomperformance\"9\n\022Set" +
      "tingRoomRequest\022\024\n\014setting_type\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t\"&\n\023SettingRoomResponse\022\017\n\007m" +
      "essage\030\001 \001(\t\":\n\022ControlRoomRequest\022\024\n\014co" +
      "ntrol_type\030\001 \001(\t\022\016\n\006action\030\002 \001(\t\"<\n\023Cont" +
      "rolRoomResponse\022\016\n\006status\030\001 \001(\t\022\025\n\rerror" +
      "_message\030\002 \001(\t2\275\002\n\024HotelRoomPerformance\022" +
      "\217\001\n\022AdjustRoomSettings\022:.grpc.example.sm" +
      "arthotelroomperformance.SettingRoomReque" +
      "st\032;.grpc.example.smarthotelroomperforma" +
      "nce.SettingRoomResponse(\001\022\222\001\n\023ControlRoo" +
      "mFeatures\022:.grpc.example.smarthotelroomp" +
      "erformance.ControlRoomRequest\032;.grpc.exa" +
      "mple.smarthotelroomperformance.ControlRo" +
      "omResponse(\0010\001B<\n&grpc.example.smarthote" +
      "lroomperformanceB\020RoomPerformance3P\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_example_smarthotelroomperformance_SettingRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_example_smarthotelroomperformance_SettingRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_example_smarthotelroomperformance_SettingRoomRequest_descriptor,
        new java.lang.String[] { "SettingType", "Value", });
    internal_static_grpc_example_smarthotelroomperformance_SettingRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_example_smarthotelroomperformance_SettingRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_example_smarthotelroomperformance_SettingRoomResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_grpc_example_smarthotelroomperformance_ControlRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_example_smarthotelroomperformance_ControlRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_example_smarthotelroomperformance_ControlRoomRequest_descriptor,
        new java.lang.String[] { "ControlType", "Action", });
    internal_static_grpc_example_smarthotelroomperformance_ControlRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_example_smarthotelroomperformance_ControlRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_example_smarthotelroomperformance_ControlRoomResponse_descriptor,
        new java.lang.String[] { "Status", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
