// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelRoomPerformance.proto

package grpc.example.smarthotelroomperformance;

public interface SettingRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.example.smarthotelroomperformance.SettingRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string setting_type = 1;</code>
   */
  java.lang.String getSettingType();
  /**
   * <code>string setting_type = 1;</code>
   */
  com.google.protobuf.ByteString
      getSettingTypeBytes();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
