// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelRoomPerformance.proto

package grpc.example.smarthotelroomperformance;

public interface SettingRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.example.smarthotelroomperformance.SettingRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
