// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelRoomLight.proto

package grpc.example.smarthotelRoomLight;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHotelRoom.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
