// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelRoomLight.proto

package grpc.example.smarthotelRoomLight;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHotelRoom.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomarea = 1;</code>
   */
  java.lang.String getRoomarea();
  /**
   * <code>string roomarea = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomareaBytes();
}
