// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelroomserive.proto

package grpc.example.smarthotelroomservice;

public final class RoomService2 {
  private RoomService2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomServiceUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomServiceUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomComponentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomComponentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomComponentUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomComponentUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032SmartHotelroomserive.proto\"$\n\022RoomServ" +
      "iceRequest\022\016\n\006roomid\030\001 \001(\t\"4\n\021RoomServic" +
      "eUpdate\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t" +
      "\"&\n\024RoomComponentRequest\022\016\n\006roomid\030\001 \001(\t" +
      "\"3\n\023RoomComponentUpdate\022\014\n\004type\030\001 \001(\t\022\016\n" +
      "\006status\030\002 \001(\t2\255\001\n\025SmartHotelRoomService\022" +
      "L\n\037SubscribeForRoomServicesUpdates\022\023.Roo" +
      "mServiceRequest\032\022.RoomServiceUpdate0\001\022F\n" +
      "\025RoomServicesComponent\022\025.RoomComponentRe" +
      "quest\032\024.RoomComponentUpdate0\001B4\n\"grpc.ex" +
      "ample.smarthotelroomserviceB\014RoomService" +
      "2P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoomServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomServiceRequest_descriptor,
        new java.lang.String[] { "Roomid", });
    internal_static_RoomServiceUpdate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomServiceUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomServiceUpdate_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_RoomComponentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RoomComponentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomComponentRequest_descriptor,
        new java.lang.String[] { "Roomid", });
    internal_static_RoomComponentUpdate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RoomComponentUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomComponentUpdate_descriptor,
        new java.lang.String[] { "Type", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
