// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHotelroomserive.proto

package grpc.example.smarthotelroomservice;

public interface RoomComponentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomComponentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomid = 1;</code>
   */
  java.lang.String getRoomid();
  /**
   * <code>string roomid = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomidBytes();
}
